### ISSUE TITLE
Error to get token

### ISSUE THREAD

**Issue by pehkope** [microsoftgraph/console-csharp-connect-sample#3] opened 2018-05-01 16:08 UTC
i am getting this error althought i register application as guided and used azure ad account. Any help?
Error detail: AADSTS90130: Application 'cbd7e3bd-21be-4f43....' (graphapi consoleapp) is not supported over the /common or /consumers endpoints. Please use the /organizations or tenant-specific endpoint.
Trace ID: 85073843-a3b8-450d-8113-400d5db22500
Correlation ID: a121d901-21dc-461f-9048-b4bfc7855f18

**Comment by jasonjoh** [comment] 2018-05-02 18:21
I cannot reproduce this. Can you provide a screenshot of your app registration?

**Comment by nguyentl1820** [comment] 2018-05-11 11:19
authResult = await IdentityClientApp.AcquireTokenSilentAsync(Scopes, IdentityClientApp.Users.First());
It was error by IdentityClientApp.Users.First() get null. How can I fix it?

**Comment by jasonjoh** [comment] 2018-05-11 16:49
@nguyentl1820 what was the error? You will get null there prior to login, so this isn't necessarily an error condition. `AcquireTokenSilentAsync` is an attempt to get a token from the cache (for cases where the user is already logged in).

**Comment by jasonjoh** [comment] 2020-05-08 20:43
Thanks for your interest in Microsoft Graph! We are archiving this sample, so I'm closing this issue. For a replacement C# console app sample, please see https://github.com/microsoftgraph/msgraph-training-dotnet-core. We apologize for any inconvenience.

**Closed as completed by jasonjoh** 2020-05-08 20:43 UTC
